### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wolfyuhd** [SebOuellette/LiveBot#100]
App not displaying any servers aswell as DMs
![image](https://user-images.githubusercontent.com/76390670/103107813-3374a380-4642-11eb-8427-dcd8277698eb.png)

**Comment by SebOuellette** [comment]
Livebot can only show servers that both the bot and the owner of the bot (hopefully you) are in. If even those servers aren't showing, then you need to make sure that [BOTH gateway intents are enabled.](https://images.soue.ca/IGB0f3qF0y.png)

**Comment by wolfyuhd** [comment]
Thank you! Presence intent wasn't checked for some reason and I really really appreciate the quick response :)

**Comment by SebOuellette** [comment]
Glad that fixed it!
