### ISSUE TITLE
Servers not shown[BUG]

### ISSUE THREAD

**Issue by MCKingSHL** [SebOuellette/LiveBot#101]
#### How major is the bug from 1 - 10
- Scale: 8

#### What branch are you using?

- Branch: Both
#### What type of bug is it?

- Type: Visual
#### Steps required to reproduce the bug

- Steps: 

#### Screenshot (In most cases required)

- Screenshot:

**Comment by SebOuellette** [comment]
Livebot can only show servers that both the bot and the bot's owner (hopefully you) are both in. If even those aren't showing, make sure you enable gateway intents on the application bot page.

**Comment by probablybased** [comment]
I have gateway intents enabled and am in the server but its still now showing.

**Comment by proudparrot2** [comment]
Hi, I am having this same problem - How does live bot know that they are in the same server as the owner?
Also I am trying to do gateway intents right now

**Comment by SebOuellette** [comment]
Livebot knows because it asks discord who the owner of the bot is.

**Comment by dcrime** [comment]
There wasn't any activity in a while so it's safe to say it can be closed.

**Comment by SebOuellette** [comment]
Good point

**Comment by IonX1** [comment]
I still can't see DMs or servers, I have all gateway intents enabled.

**Comment by magmitique** [comment]
```fix
We don't need to be the server owner or an admin ?
```

**Comment by anubis836** [comment]
how do i enable gateway intents
