### ISSUE TITLE
[BUG] servers and dm message not shown but i can see my server and dm message in other bot client

### ISSUE THREAD

**Issue by Shiu3412** [SebOuellette/LiveBot#102]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: executable
#### What type of bug is it?

- Type: visual
#### Steps required to reproduce the bug

- Steps: login the bot account and then it doesnt display any servers or dm message

#### Screenshot (In most cases required)

- Screenshot:
![image](https://user-images.githubusercontent.com/43491356/104862842-2d3ac400-596f-11eb-82bd-e4e11417b2fa.png)

this is the screenshot that i use other bot client to login
![image](https://user-images.githubusercontent.com/43491356/104862920-6b37e800-596f-11eb-88ff-954ccc3f3a50.png)

**Comment by nearlySplat** [comment]
LiveBot requires the GuildMember and Presence intents to be enabled on your bot.

Additionally, it can only show servers the bot owner and bot are in.

**Comment by SebOuellette** [comment]
Closing this since the correct answer was given, and there has not been any activity.
