### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Motzumoto** [SebOuellette/LiveBot#106]
#### How major is the bug from 1 - 10
- Scale:  10, removes mosft if not all of the functionality 

#### What branch are you using?

- Branch: Executable 
#### What type of bug is it?

- Type: Servers nor DMs are shown
#### Steps required to reproduce the bug

- Steps: Login to the bot token and just wait for it to load, when it does. no servers or dms are shown

Its signed into a working token, but i hid the name of the bot for obvious reasons since its verified. 

![image](https://user-images.githubusercontent.com/45925152/109618366-743ade00-7b05-11eb-9e4a-89616547091b.png)

**Comment by dcrime** [comment]
The executable hasn't been updated for some time but I don't think that's really the issue.
Here's a couple of questions to troubleshoot this.
How many servers is your bot in?
Do you share a server with the bot?
Are the privileged gateway intents turned on the bot?

**Comment by Motzumoto** [comment]
> The executable hasn't been updated for some time but I don't think that's really the issue.
> Here's a couple of questions to troubleshoot this.
> How many servers is your bot in?
> Do you share a server with the bot?
> Are the privileged gateway intents turned on the bot?
> 
> Oh also an important question, are you the bot owner? Since the bot compares to the owner

My bot is in 127 servers
I share quite a few servers with my bot.
The only privileged gateway that i have available is Guild Members. I wasnt given Presence intents. 
And yes, of course, Im the bot owner.

**Comment by dcrime** [comment]
I was sure this would happen at some point, basically the project needs some fixing which **cough** hasn't happened in a long time, unless you can somehow get the presence intents or fix the code yourself (or the least likely the creator fixes it), you won't be able to use LiveBot.
Basically the main bugs can easily be fixed though **someone** doesn't want to fix it themselves and has "fired" people who would

**Comment by Motzumoto** [comment]
Damn, yeah i cant just get presence intent enabled because for some reason its incredibly hard to get. And members intent took  *months* to get. Thank you either way

**Comment by SebOuellette** [comment]
Yeah, my apologies for not being able to fix it. I'm currently swamped in my last year of high school, but that presence intent will be fixed as soon as I have anything that could be construed as free time.

**Comment by Motzumoto** [comment]
> Yeah, my apologies for not being able to fix it. I'm currently swamped in my last year of high school, but that presence intent will be fixed as soon as I have anything that could be construed as free time.

Alright cool. thank you for replying, please keep us updated if you can
