### ISSUE TITLE
[SUGGESTION] The reply feature

### ISSUE THREAD

**Issue by NitroDisPro** [SebOuellette/LiveBot#107]
This is a great tool. I've been wondering if adding replies was possible?

**Comment by SebOuellette** [comment]
Thank you! 

While this is definitely possible, there are other much more important features and bug fixes to me made first. This probably won't be added for a while, especially since I'm swamped in my last year of high school.

**Comment by SebOuellette** [comment]
Closing because this should go into discord anyways

**Comment by NitroDisPro** [comment]
Nice! I wish I can help with this project but I know nothing about programming, I've only messed around

**Comment by nearlySplat** [comment]
Just because the maintainer is busy doesn't mean the whole of GitHub is ignorant of what's happening here.

I'll take a look and see what I can do.

**Comment by NitroDisPro** [comment]
> Just because the maintainer is busy doesn't mean the whole of GitHub is ignorant of what's happening here.
> 
> I'll take a look and see what I can do.

ok
