### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dylanjamesdev** [SebOuellette/LiveBot#109]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: Master
#### What type of bug is it?

- Type:  Backend
#### Steps required to reproduce the bug

- Steps: Clone from repo, npm i, npm test

#### Screenshot (In most cases required)

- Screenshot:

The application does not list any servers, clicking the servers button does nothing-- the page does not change.

**Comment by SebOuellette** [comment]
For anyone in the future wondering how to fix this, you need to enable both gateway intents on your discord applications page. [EXAMPLE](https://images.soue.ca/IGB0f3qF0y.png)
