### ISSUE TITLE
Freeze on "Getting the owner of the bot"

### ISSUE THREAD

**Issue by KifoPL** [SebOuellette/LiveBot#110]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: executable
#### What type of bug is it?

- Type: crash on loading screen ("Getting the owner of the bug")
#### Steps required to reproduce the bug

- Steps: I simply attempt to open executable, it immediately freezes on *getting the owner of the bot*. I deleted all files and redownloaded the branch, same error.

#### Screenshot (In most cases required)

- Screenshot: [link](https://i.imgur.com/4CF1e93.png) *(idk how this can help, but yeah it freezes on this frame)*

**Comment by KifoPL** [comment]
I've tried manual branch too and I get the same error.

**Comment by SebOuellette** [comment]
Is the app completely frozen, or is it just not progressing?

**Comment by SebOuellette** [comment]
yeah the bot token is stored in some program files folder. To reset it, press ctrl+shift+i, click console, then type in localStorage.clear()

Hopefully this fixes your issue. I don't know why the bot would freeze unless your bot is in an extremely large number of servers and has a large number of users

**Comment by KifoPL** [comment]
Can't even hit ctrl+shift+i because it freezes before this shortcut initializes. I don't wanna clear storage of my Discord app. Why not just store it hashed within main dir?
The server it freezes upon has 10 000 messages, ~90k messages daily, and a bit over 400 channels. Maybe you should restrict entering too big servers if it's getting immediately frozen?

**Comment by SebOuellette** [comment]
You don't have to clear storage of the discord app... localStorage.clear() only clears it for whatever app you're entering that into, so, only livebot. It will be stored locally soon, I just am looking for time to work on it. Same goes for the channels, it needs some heavy optimizations.

**Comment by nearlySplat** [comment]
Storing a token locally isn't the best of ideas in my opinion, you should just stay with localStorage.
