### ISSUE TITLE
not receiving any dm's and it doesn't show any servers that my bot is in

### ISSUE THREAD

**Issue by camperramper** [SebOuellette/LiveBot#111]
#### How major is the bug from 1 - 10
- Scale: 

#### What branch are you using?

- Branch:
#### What type of bug is it?

- Type: 
#### Steps required to reproduce the bug

- Steps:

#### Screenshot (In most cases required)

- Screenshot:

**Comment by SebOuellette** [comment]
You most likely forgot to enable both gateway intents in discord's bot application panel.

**Comment by SebOuellette** [comment]
Also, please fill out the template next time. It helps me gain more information about the nature of your problem, meaning you'll get a faster and more accurate answer. :)
