### ISSUE TITLE
Can't see servers or DM

### ISSUE THREAD

**Issue by Oakchris1955** [SebOuellette/LiveBot#114]
#### How major is the bug from 1 - 10
- Scale: 8

#### What branch are you using?

- Branch: executable
#### What type of bug is it?

- Type: Visual
#### Steps required to reproduce the bug

- Steps: Open the executable

#### Screenshot (In most cases required)

- Screenshot: 
![image](https://user-images.githubusercontent.com/80592203/114743102-07963e80-9d55-11eb-8cea-1d7ee5f5737c.png)

**Comment by Oakchris1955** [comment]
Also, from what I see from closed issues, a guy named Moderpo was experiencing the same thing

**Comment by Oakchris1955** [comment]
I also tried download the master branch. Same result

**Comment by LegitMagic** [comment]
I am having the same issue

**Comment by Oakchris1955** [comment]
Found the solution @LegitMagic 
![image](https://user-images.githubusercontent.com/80592203/114744806-c0a94880-9d56-11eb-926e-7ab5dae0e0ca.png)
Make sure these are on
