### ISSUE TITLE
Can't even see the servers.

### ISSUE THREAD

**Issue by redacted079** [SebOuellette/LiveBot#115]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: Execute
#### What type of bug is it?

- Type: Visual
#### Steps required to reproduce the bug

- Steps: I have no idea.

#### Screenshot (In most cases required)

- Screenshot:
![helpls](https://user-images.githubusercontent.com/83626928/116959033-61aa6580-ac6a-11eb-811d-ccedc67add70.png)

**Comment by redacted079** [comment]
I click on servers and scripts and it just flashes red, IDK why.

**Comment by Oakchris1955** [comment]
![image](https://user-images.githubusercontent.com/80592203/117029362-3cb80000-ad07-11eb-9d7a-d5eeee132660.png)
@redacted079  Go to Discord Developers tab, then applications and bot. Make sure these are on and retry

**Comment by dcrime** [comment]
> I click on servers and scripts and it just flashes red, IDK why.

Those two features were actually planned a long time ago but never added, it's flashing red to say it's not implemented and if I'm not wrong, it should even display in the console that they're not implemented (Not sure if I added that or not)

**Comment by ikegami** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/80592203/117029362-3cb80000-ad07-11eb-9d7a-d5eeee132660.png)
> @redacted079 Go to Discord Developers tab, then applications and bot. Make sure these are on and retry

This is exactly what was needed, thanks!

**Comment by SebOuellette** [comment]
The correct answer was given, so I'm going to close this now.
