### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tonkyboi1** [SebOuellette/LiveBot#118]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: executable
#### What type of bug is it?

- Type:  I don't know, maybe both
#### Steps required to reproduce the bug

- Steps: Just join the thing and do anything, i meant try to do anything

#### Screenshot (In most cases required)

- Screenshot:
![Screenshot 2021-07-09 124442](https://user-images.githubusercontent.com/87203360/125117198-7ca6b500-e0b3-11eb-8ddc-a4bec94ab277.png)

**Comment by Tonkyboi1** [comment]
Also, my bot was invited to servers, that red one is home and there is nothing else

**Comment by Tonkyboi1** [comment]
UPDATE: it now shows 1 server, not the rest

**Comment by Oakchris1955** [comment]
![image](https://user-images.githubusercontent.com/80592203/125161294-2b1d2980-e18a-11eb-9bb7-74c063f95cc8.png)
Are these turned on in the bot application?

**Comment by Tonkyboi1** [comment]
Yes, Yes they are

**Comment by SebOuellette** [comment]
It only shows servers that both YOU and your bot are in. And by you, I mean the account that is the owner of the bot. Make sure you're in the same servers as the bot.

**Comment by Tonkyboi1** [comment]
oh, thx

**Comment by SebOuellette** [comment]
No prob :)
