### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Reallondoner** [SebOuellette/LiveBot#119]
#### How major is the bug from 1 - 10
- Scale: 10 (cant use the app)

#### What branch are you using?

- Branch: both
#### What type of bug is it?

- Type: probably both or just visual
#### Steps required to reproduce the bug

- Steps: start up the app with the login screen, paste the token in and watch the magic happen

#### Screenshot (In most cases required)

- Screenshot: 
![image](https://user-images.githubusercontent.com/87261374/125189169-fc10c180-e236-11eb-8308-08725b2d20aa.png)

**Comment by Reallondoner** [comment]
all gateway intents are on if someone was gonna ask

**Comment by SebOuellette** [comment]
Press `ctrl+shift+i` then click `console`, paste in `localStorage.clear()`. Then restart LiveBot

**Comment by Reallondoner** [comment]
i cleared the storage, now when i try to log in and save as default it gets stuck on this:
![image](https://user-images.githubusercontent.com/87261374/125198252-663e5c00-e261-11eb-826c-4da679f4483a.png)
restarting makes it get stuck on logging in aka just what i described before.
however clicking "one time login" makes it get stuck on "fetching token".
![image](https://user-images.githubusercontent.com/87261374/125198299-abfb2480-e261-11eb-9af8-2b586928a4dd.png)
hope this helps a bit on resolving it

**Comment by SebOuellette** [comment]
I believe this may be a problem with your firewall. Try allowing Livebot.exe through it (likely the default Windows Defender firewall), or disable it entirely and see if the problem persists.

**Comment by Reallondoner** [comment]
somehow doesnt work... disabled the firewall entirely (images as proof)
![image](https://user-images.githubusercontent.com/87261374/125258478-ac95c880-e2fe-11eb-8b3a-2a7787c297d2.png)
![image](https://user-images.githubusercontent.com/87261374/125258480-ad2e5f00-e2fe-11eb-9fe5-c7d90fc53ccd.png)

**Comment by SebOuellette** [comment]
I updated executable branch last night, can you try reinstalling? Also don't download from the branch, download the v1.0.0 release

**Comment by Reallondoner** [comment]
downloaded the 1.0.0 release, made my bot join a test server, disabled windows firewall (again), cleared the cache, gateway intents enabled and somehow it still gets stuck on "loading resources". downloaded both the .exe and source code and put them both in the same directory

**Comment by Reallondoner** [comment]
sorry, i didnt see the new v1.0.1 and it works. thank you for your effort

**Comment by JustSkeppYT** [comment]
hi
