### ISSUE TITLE
Loading bar gets stuck at Loading Scripts

### ISSUE THREAD

**Issue by DUCKONAROLL** [SebOuellette/LiveBot#120]
Like the title. Tried nearly everything on Stuck Loading, to no avail. Weirdly, I could sign in the first time, but when I activated Presence Intent so I could actually see the servers, this glitch started occurring. Screenshots:
![image](https://user-images.githubusercontent.com/71863699/126232879-f238cd2f-c004-4e06-bcf0-72e7d6bb92a0.png)
![image](https://user-images.githubusercontent.com/71863699/126232884-87763120-d283-4eac-b85a-fe212ddff99a.png)

**Comment by SebOuellette** [comment]
This was solved in the Discord support server. 

### Problem
For anyone in the future having this issue, if the exe file has been moved to another folder other than the main directory of LiveBot, or if you are opening the exe via an OS file search (like the search bar in the bottom left of Windows) then the app doesn't know what directory it is in.

### Solution (temporary)
To start LiveBot, you need to either open the executable file directly, or create a shortcut and open that. So far any other means is hit and miss.
