### ISSUE TITLE
Servers with animated icons fail to load.

### ISSUE THREAD

**Issue by Rainbonium** [SebOuellette/LiveBot#125]
#### What branch are you using?
- Branch: Master

#### Errors

![image](https://user-images.githubusercontent.com/66752661/130832690-edcbf100-5646-45b3-acd0-3d99d3db2119.png)

#### Steps required to reproduce the bug
Install windows branch and login to bot with gateway intent.
- Steps:
I don't know how to fix it in terms of features, but to temporarily fix it, you can delete the line of code from livebot > resources > app > js > guildsList.js (code lines shown in the screenshot below) with your java editor (I used Visual Studio). Of course this means that the gif of the server won't be animated, but it's a small price to pay for now.

#### Screenshot 
- Screenshot:
 ![DeleteCode](https://user-images.githubusercontent.com/66752661/130832253-69a3c43b-13c4-4001-87f1-cc4d4cd7ccf5.PNG)
For those who wish to have a temporary fix delete the highlighted code.
Here's how it looks with the code deleted:
![image](https://user-images.githubusercontent.com/66752661/130833072-5b4a5c4f-090b-4c4f-aa77-0df2052a2425.png)

#### Description
I'm new to GitHub so sorry if I'm unclear. Hope this is helpful!

**Comment by SebOuellette** [comment]
A proper fix for this was implemented in 0a7c2c4b251d3e6c7b0cc26133a15bce68aebbb7

**Comment by ashersasson** [comment]
im still having this error, even though I have the latest release, which from what i see fixes this issue

**Comment by SebOuellette** [comment]
I doubt your issue is the same. Try enabling both gateway intents in the discord developer portal.
