### ISSUE TITLE
SERVERS DON'T APPEARS

### ISSUE THREAD

**Issue by mariocmg** [SebOuellette/LiveBot#128]
#### What branch are you using?

- Branch: Executable

#### Errors

![image](https://user-images.githubusercontent.com/38396612/131371027-8d229208-d08f-47c4-bd2b-21d62ab87f6b.png)

#### Steps required to reproduce the bug

- Steps: I open the app and any server appear

#### Screenshot (In most cases required)

- Screenshot: 
![image](https://user-images.githubusercontent.com/38396612/131371135-30d1d06e-e304-4b8e-bb95-0b1dccc8c8ea.png)

**Comment by mariocmg** [comment]
Doing the last thing you mentioned solved it. One question, can you send videos and edit messages?

**Comment by SebOuellette** [comment]
You can't send files yet, but if you have a link to the video then you can send that and it will embed through discord.

Yes you can edit messages. Just right click, and press edit. 

Glad it works for you! 👌
