### ISSUE TITLE
mac: servers and dms not working

### ISSUE THREAD

**Issue by exi-st** [SebOuellette/LiveBot#131]
Using Mac, Big Sur.
I cant see or reply to my test dms sent from my main to the bot account and i can see but cannot enter the servers the bot is in

**Comment by SebOuellette** [comment]
Try running LiveBot as Sudo. There seems to be a permissions issue currently.

**Comment by AstroOrbis** [comment]
This seems to be fixed if you clone the project and use `npm start` for some reason

**Comment by CrumplesHQ** [comment]
Having this issue as well, I know this is dumb as well, but how would we run it with Sudo? After cd'ing into it, what should I do?

**Comment by CrumplesHQ** [comment]
I'm having the same issue, I ran it as Sudo to no avail. Any current solutions?

**Comment by ForBai** [comment]
linux has the same bug still

**Comment by SebOuellette** [comment]
Linux shouldn't have this bug, I wrote this project on linux and the release has no issues on my side. Try using sudo?

**Comment by SebOuellette** [comment]
Closing. For related discussion about this issue, please use issue  #227 instead.
