### ISSUE TITLE
[win] dms not loading

### ISSUE THREAD

**Issue by grand11** [SebOuellette/LiveBot#133]

**Comment by AstroOrbis** [comment]
Reproducible on MacOS M1

**Comment by SebOuellette** [comment]
Can either of you open developer tools and screenshot the console output?

**Comment by AstroOrbis** [comment]
<img width="546" alt="Screen Shot 2021-09-29 at 13 36 31" src="https://user-images.githubusercontent.com/65419194/135320170-77e16148-9655-40ca-8272-33ce3bf72121.png">

**Comment by SebOuellette** [comment]
Alright well there's no errors. So what happens when you dm the bot? Just nothing appears? Try dming using livebot by right-clicking a member in the member list.

**Comment by AstroOrbis** [comment]
It works now idk why :3
