### ISSUE TITLE
When downloading 1.1.2 alpha, 1.1.1 gets installed on mac

### ISSUE THREAD

**Issue by ashersasson** [SebOuellette/LiveBot#134]
#### What branch/release are you using?

- Branch/Release: downloaded 1.1.2 alpha

#### Errors
 
![image](https://user-images.githubusercontent.com/31999481/133277777-83dd562a-3d5e-4bab-83f6-2b2977ced529.png)

#### Steps required to reproduce the bug

- Steps: 
- download livebot-darwin-x64.zip from https://github.com/SebOuellette/LiveBot/releases/tag/v1.1.2-alpha 
- expand the zip file
- open the app > go to the about menu and notice that v1.1.1 was installed

#### Screenshot (In most cases required)

- Screenshot:

**Comment by SebOuellette** [comment]
Yeah I just forgot to change the version number when packaging it.

**Comment by ashersasson** [comment]
well I'm running into the issue in #125 which is why I guessed it didn't install the correct file, it shows server icons that arent animated but don't show animated ones, i have all intents enabled

**Comment by SebOuellette** [comment]
Are the animated icons for servers that both the owner and the bot are in? Beacuse livebot can only show servers that both the bot and it's owner are in

**Comment by ashersasson** [comment]
yes, both the bot owner and the bot are in the server

**Comment by SebOuellette** [comment]
Alright can you press cmd+shift+i, click console, and then screenshot the output?

**Comment by ashersasson** [comment]
![image](https://user-images.githubusercontent.com/31999481/133282803-59e99db4-d8fe-40f1-aea1-37254be7f6ed.png)

**Comment by ashersasson** [comment]
and if you want i can take this to the discord server if that's easier

**Comment by SebOuellette** [comment]
Yeah that would be better probably

**Comment by SebOuellette** [comment]
Problem was that the server was too large, 140,000+ members, and livebot isn't optimized enough to handle that.
