### ISSUE TITLE
Not all servers are listed

### ISSUE THREAD

**Issue by devojunky** [SebOuellette/LiveBot#135]
#### What branch/release are you using?

- Branch/Release: LiveBot v1.1.2 alpha release

#### Errors

n/a

#### Steps required to reproduce the bug

- Steps: Invite to a server via the OAuth2 link generator in the Discord developer portal with admin permissions and slash command permissions.

#### Screenshot (In most cases required)

- Screenshot: 
![image](https://user-images.githubusercontent.com/48422732/133877597-02b06acd-5ad0-4ded-8074-8c11a17a0f51.png)
![image](https://user-images.githubusercontent.com/48422732/133877657-d1a0cc4f-9c1b-49aa-9006-528cad6b82e2.png)

#### Description

Only some servers are listed on the server list despite it being invited to said server. I went through all the common troubleshooting steps (enable gateway intents etc.).

**Comment by SebOuellette** [comment]
Livebot can only show servers that both the bot's creator and the bot are both in.

**Comment by devojunky** [comment]
Why would this be a limitation? A bot with the right permissions would theoretically be able view servers that the creator isn’t in right?

**Comment by SebOuellette** [comment]
Yes, but discord staff contacted me and told me that because of some privacy agreement, LiveBot can't show messages that the user wouldn't be able to see in the normal discord client.
