### ISSUE TITLE
I use scratch blocks

### ISSUE THREAD

**Issue by RRRandom-Youtube** [SebOuellette/LiveBot#138]
#### What branch/release are you using?

- Branch/Release:

#### Steps required to reproduce the bug

- Steps:

#### Screenshot (In most cases required)

- Screenshot:

#### Description

@[](url)

**Comment by SebOuellette** [comment]
I know you gave me a TON of information to go off here.. but can you give me a little more? Maybe fill out that handy little template, and let me know how on earth scratch blocks relate to this project.

**Comment by NorthX78** [comment]
> I know you gave me a TON of information to go off here.. but can you give me a little more? Maybe fill out that handy little template, and let me know how on earth scratch blocks relate to this project.

I have no idea either LOLLL, I think they mean that they don't know how to execute it...?? maybe they want you to add scratch compatibility. Not sure.

**Comment by SebOuellette** [comment]
Ok I'm closing this now since it doesn't seem to relate to this project in any way
