### ISSUE TITLE
servers not showing up

### ISSUE THREAD

**Issue by ducksucker** [SebOuellette/LiveBot#143]
Hello, so as the title says, I can't see server the bot is in (yes the bot is in 2 servers, with Admin permissions).
I'm using latest version. (Windows 10)
I have even tried to click on the servers button, inside of user options, that didn't do anything though.
Answer / Help would be greatly appreciated

![image](https://user-images.githubusercontent.com/73056239/136258689-7b5175b7-7def-4da5-9eaa-7b3068fee0dd.png)

**Comment by IIRobotNinjaII** [comment]
yah same.

**Comment by vens8** [comment]
Same.

**Comment by SebOuellette** [comment]
Turn on both gateway intents on your application page.

**Comment by Martinka031** [comment]
> Turn on both gateway intents on your application page.

its still not working
