### ISSUE TITLE
No Servers or DMs loading

### ISSUE THREAD

**Issue by omerhijazi404** [SebOuellette/LiveBot#144]
#### What branch/release are you using?

- Branch/Release:
   latest

#### Steps required to reproduce the bug

- Steps:
  Started livebot but there are no dms or servers loading

#### Screenshot (In most cases required)

- Screenshot:
![image](https://user-images.githubusercontent.com/65223292/139808243-74c7f913-1441-4bfd-b0a4-d6da168c74e2.png)

**Comment by omerhijazi404** [comment]
just had to enable all intents

**Comment by KlausNieto** [comment]
Didnt work for me. Any solutions?

**Comment by SebOuellette** [comment]
Livebot can only show servers that the owner account and the bot are both in.

**Comment by ducanh2002123** [comment]
Well, I personally do not see why it only shows servers that both are currently in. probably this one is a limitation imposed by LiveBot's dev themselves,

**Comment by RoryNesbitt** [comment]
Is the owner account automatically retrieved? I just downloaded today and I'm getting this issue even though I share several servers with my bot

**Comment by intLostDev** [comment]
> Livebot can only show servers that the owner account and the bot are both in.

mine does still has issue

**Comment by SebOuellette** [comment]
> Well, I personally do not see why it only shows servers that both are currently in. probably this one is a limitation imposed by LiveBot's dev themselves.

Correct. Discord contacted me and told me that it could cause a privacy issue if bots can show all messages, so I limited it.
