### ISSUE TITLE
can't zoom in!

### ISSUE THREAD

**Issue by Bardia-SG** [SebOuellette/LiveBot#149]
#### What branch/release are you using?

- Branch/Release: v1.1.2 alpha release
its able to zoom out using ctrl & - buttons combination but its not able to zoom in using ctrl & + buttons !
- Screenshot:
![image](https://user-images.githubusercontent.com/77557756/144716569-31416b8c-957c-4d17-9582-e218582d9d07.png)

**Comment by SebOuellette** [comment]
Use ctrl,shift,+
