### ISSUE TITLE
Barry not working

### ISSUE THREAD

**Issue by bisselwil** [SebOuellette/LiveBot#150]
Every time i use Barry with /help, he responds, but it is blank. i'm using the latest stable version of Livebot
<img width="785" alt="Screen Shot 2021-12-04 at 3 43 52 PM" src="https://user-images.githubusercontent.com/69834556/144724046-80b809e2-95dc-4ece-a390-d9a755c5dea3.png">. 
.

**Comment by SebOuellette** [comment]
Barry hasn't been updated since the message display system has. I'll let you know when this is fixed.
