### ISSUE TITLE
Missing start script

### ISSUE THREAD

**Issue by rich1488** [SebOuellette/LiveBot#151]
#### What branch/release are you using?

- Branch/Release: 1.1.3

#### Errors

`pi@tradehubrpi:~/discordbots/livebot $ npm start
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-12-10T19_42_54_357Z-debug.log
`

#### Steps required to reproduce the bug

- Steps: `npm install` then `npm start`

#### Description

Trying to do this on a Raspberry Pi

**Comment by SebOuellette** [comment]
You said you're using a release, but a release just contains an executable. You don't need to use npm for a release.
