### ISSUE TITLE
 THE CODE EXECUTION CANNOT PROCEED because ffmoeg.dll was not found

### ISSUE THREAD

**Issue by GodStashP** [SebOuellette/LiveBot#152]
#### What branch/release are you using?
 Latest
- Branch/Release:Latest Version

#### Errors

THE CODE EXECUTION CANNOT PROCEED because ffmoeg.dll was not found 

#### Steps required to reproduce the bug

- Steps:

#### Screenshot (In most cases required)

- Screenshot:

**Comment by SebOuellette** [comment]
This happens quite frequently, and it's due to the user's inability to understand what a zip file is, and how to use it. Tip: you need to extract the whole zip file BEFORE executing the executable.
