### ISSUE TITLE
Add light theme

### ISSUE THREAD

**Issue by michelle1574** [SebOuellette/LiveBot#154]
I hate dark Discord theme and I like light theme but there isn't an option to change the theme. Can you add the feature?

**Comment by DarkGuy10** [comment]
Jesus christ-

**Comment by M4rlus** [comment]
BAN THIS BAN THIS BAN THIS

**Comment by michelle1574** [comment]
What do you mean "ban this"? I'm not normal for themes. I'm not using default ones.

**Comment by SebOuellette** [comment]
I will not be adding a light theme. Custom themes are supported by default though, so feel free to write your own and put it in the themes folder.
