### ISSUE TITLE
Servers not showing up

### ISSUE THREAD

**Issue by brentspine** [SebOuellette/LiveBot#156]
#### What branch/release are you using?

- Branch/Release:
v1.1.3 alpha release

#### Steps required to reproduce the bug

- Steps:
No servers show up when logging into any bot account, also no DMs or anything.
The Change presence options work

#### Screenshot (In most cases required)

- Screenshot:
https://i.imgur.com/82WxJEK.jpg
https://i.imgur.com/8pSjHuo.jpg

**Comment by PatrickMSM** [comment]
same issue here

**Comment by DevourerOfGod** [comment]
yup

**Comment by SebOuellette** [comment]
#157
