### ISSUE TITLE
zostalem zawirusowany po uzyciu oprogramowania

### ISSUE THREAD

**Issue by underthebox** [SebOuellette/LiveBot#159]
#### What branch/release are you using?

- Branch/Release:

#### Steps required to reproduce the bug

- Steps:

#### Screenshot (In most cases required)

- Screenshot:

**Comment by SebOuellette** [comment]
Issues must be made in english, and the template must be filled out. This translates to "I was infected while using this software". Livebot is not a virus, and no claim can be made. It's open source, and you can see all the code.
