### ISSUE TITLE
Guilds do not show up for bots owned by teams

### ISSUE THREAD

**Issue by F43nd1r** [SebOuellette/LiveBot#161]
#### What branch/release are you using?

- Branch/Release: master

#### Errors

Guilds do not show up in bots owned by a team.

#### Steps required to reproduce the bug
- Create new discord developer team
- Create or move a bot to that team
- Add bot to a guild
- Try to access that guild in LiveBot, does not show up

#### Description

No errors in console, it just says "adding guilds". Login seems to work.

**Comment by SebOuellette** [comment]
I own a bot in a team, and it shows the guilds.

Ensure that the user you selected that is controlling the bot is inside the same servers as the bots, or the servers will not display. Also ensure that ALL gateway intents are enabled for the bot.
