### ISSUE TITLE
I dont see my servers

### ISSUE THREAD

**Issue by xerix123456** [SebOuellette/LiveBot#166]
Hi.

I invited the bot to my server but I can't see it
I can see it on the server
I use version **1.1.3-alpha** and my OS is **Windows 11**

**Comment by SebOuellette** [comment]
Enable all the gateway intents.

**Comment by Z3R0C1PH3R** [comment]
Okay My bad, My Detect Presence intent was turned off somehow even tho i remember turning it on

> Enable all the gateway intents.
