### ISSUE TITLE
Stuck on "Loading Resources" Text

### ISSUE THREAD

**Issue by naxce** [SebOuellette/LiveBot#167]
#### What branch/release are you using?
LiveBot v1.1.3 alpha release

#### Errors
Loading stuck on "Loading Resources"

![obraz](https://user-images.githubusercontent.com/92225052/153720949-9a7c4583-23f2-4b11-a30e-c38ba69af136.png)

**Comment by SebOuellette** [comment]
Turn on all gateway intents. 

If you are on Mac, unfortunately the release won't work so you'll have to use source.
