### ISSUE TITLE
Status disappears now and then

### ISSUE THREAD

**Issue by RobinRMC** [SebOuellette/LiveBot#172]
#### Version
- Release: v1.1.3-alpha

#### Steps required to reproduce the bug
- Steps: Set a status (can be both text or availability status), wait a few minutes & see.

**Comment by yesBad** [comment]
I don't believe its a bug exactly... It just hasn't been made to stay for more than 15min I don't think

**Comment by RobinRMC** [comment]
But sometimes it disappears within like 5 minutes or something.

**Comment by SebOuellette** [comment]
Fixed in the latest commit
