### ISSUE TITLE
Bot's token is "too long"

### ISSUE THREAD

**Issue by SkzzyLoldx** [SebOuellette/LiveBot#174]
i'm using a recent version of livebot and when i went to input the bot's token, t said that it's too long.
![image](https://user-images.githubusercontent.com/104641403/165976982-282277de-fcca-4ff0-a833-e764d3ffe0f2.png)

**Comment by Gazirovich** [comment]
Same problem here

**Comment by danielftosta-176** [comment]
same

**Comment by KeroxI** [comment]
same

**Comment by MCUxDaredevil** [comment]
Same issue

**Comment by yesBad** [comment]
This has been fixed in the source version.
