### ISSUE TITLE
You cannot click on servers.

### ISSUE THREAD

**Issue by DaBoiCJ6241** [SebOuellette/LiveBot#175]
https://github.com/SebOuellette/LiveBot/issues/176
#### What branch/release are you using?

- Branch/Release: latest

#### Steps required to reproduce the bug

- Steps:

#### Screenshot (In most cases required)

- Screenshot:

#### Description

You cannot click on servers.
macOS 10.15

**Comment by shubhamshah02** [comment]
Having the same issue.

**Comment by SebOuellette** [comment]
Can you please fill out the template and take a screenshot.

**Comment by CJFitchett79** [comment]
Done.

**Comment by SebOuellette** [comment]
Mac has this issue sometimes with the release, it's a permissions issue which I have tried to solve, but wasn't able to. Use node.js and the source (instructions can be found on the readme) if you are on mac

**Comment by SebOuellette** [comment]
Closing. Please refer to #227 for further discussion about this issue.
