### ISSUE TITLE
I cant click on servers. (Following)

### ISSUE THREAD

**Issue by DaBoiCJ6241** [SebOuellette/LiveBot#176]
#### What branch/release are you using?

- Branch/Release: master

#### Errors

![Screen Shot 2022-05-06 at 2 32 18 AM](https://user-images.githubusercontent.com/82349171/167106221-fce55ac2-3054-4074-8576-330733f533c9.png)

#### Steps required to reproduce the bug

- Steps: Launch app, put in token, try and click on a server

#### Screenshot (In most cases required)

- Screenshot:

#### Description

macOS 10.15
Homebrew installed

**Comment by yesBad** [comment]
Can you show the actual error.... ???

**Comment by atreydesai** [comment]
Same thing happens to me. I can see the server but nothing happens when I click on the server icon.

**Comment by atreydesai** [comment]
Using a Macbook

**Comment by SebOuellette** [comment]
There is sometimes a permissions issue on mac. You have to build from source instead of using the executable

**Comment by SebOuellette** [comment]
Closing. Please refer to #227 for further discussion about this issue.
