### ISSUE TITLE
Issue name goes here

### ISSUE THREAD

**Issue by thekoreandoctor** [SebOuellette/LiveBot#184]
Release: livebot-win32-x64.zip

screenshot:
![screencap](https://user-images.githubusercontent.com/85131193/173207526-4f6fb903-2a18-4e14-903c-c626c983aa4f.png)
 
I can't see any dms or servers im in. 

![image](https://user-images.githubusercontent.com/85131193/173207606-adbcef69-99c4-4ddd-8df3-58cd336cc5e4.png)
is in the server too ^

**Comment by SebOuellette** [comment]
Didn't even fill out the issue name.

Livebot only shows servers that both the bot, and the bot's owner account, are in.
