### ISSUE TITLE
Suggestion: add reply message feature

### ISSUE THREAD

**Issue by GPBR815** [SebOuellette/LiveBot#202]
Based on my experience with livebot, it would be great if the feature of replying messages were implemented, because sometimes in a active server, you want to reply an specific message, but the message ends up becomming far away in question of seconds, and in these times, i really miss this feature, that said, i don't have any complaints about the app, the app is great and saved me much times, keep it with the good work

**Comment by yesBad** [comment]
Already suggested. Use Discord for suggestions btw.
