### ISSUE TITLE
Cannot close/minimise/maximise application

### ISSUE THREAD

**Issue by dommilosz** [SebOuellette/LiveBot#203]
#### What branch/release are you using?

- Branch/Release:
LiveBot v1.1.5 alpha release 

#### Errors
![obraz](https://user-images.githubusercontent.com/54410730/189221370-dafa8518-a2fe-4ec9-a353-5a36d3a8fb2e.png)

#### Steps required to reproduce the bug

- Steps:
- Open LiveBot
- Try to alter window state / close the app

#### Screenshot (In most cases required)

- Screenshot:
![obraz](https://user-images.githubusercontent.com/54410730/189220468-b559d9bb-5522-4d98-940f-9fd7d61e731a.png)

#### Description

After clicking any of the 3 buttons it didn't do anything.

Platform: Windows 10 64b

**Comment by AlzheTV** [comment]
Hi.

Just updated in the last minute. Same thing.
