### ISSUE TITLE
"Join Server" button for bot accounts

### ISSUE THREAD

**Issue by SylveonBottle** [SebOuellette/LiveBot#21]
Please add a feature similar to discord's "Join/Make New Server" button, but when clicked it generates an OAuth2 link that you can give to admins to invite your bot.

This way, when I want to join a friend's server, I can generate the link and give it to them to be invited.

**Comment by Lenart12** [comment]
Why not use this? https://discordapi.com/permissions.html

**Comment by SebOuellette** [comment]
A section in the user settings menu to generate an invite link has been added (and is stable) in commit 98fcf621d46a1e12c30ff1a8e16e3873050e04cb
