### ISSUE TITLE
Doesn't show channels in server

### ISSUE THREAD

**Issue by solomonsweb** [SebOuellette/LiveBot#212]
I'm on mac and i cant get any servers or channels.
<img width="1440" alt="Screenshot 2022-10-09 at 11 49 24 AM" src="https://user-images.githubusercontent.com/99205887/194752744-526b3687-bba4-4cc0-9538-bfbd67a0c2dc.png">

**Comment by SebOuellette** [comment]
It appears Livebot has issues on mac when you use the release. Download the source code and follow the [manual install instructions](https://github.com/SebOuellette/LiveBot#from-source-unstable), and it should work on mac.

**Comment by Tyrsus666** [comment]
i have the same issues on windows

**Comment by SpyKai0808** [comment]
same

**Comment by SebOuellette** [comment]
If you have this issue on windows, then you need to enable all the gateway intents on your bot's configuration page in [discord.dev](https://discord.dev/).

If you have this issue on mac, then use source rather than release, and refer to the many other open issues regarding this.
