### ISSUE TITLE
All servers not showing up

### ISSUE THREAD

**Issue by Deemitry88** [SebOuellette/LiveBot#213]
I only see the servers that i (bot creator) am in. Is that normal ? Because it destroy all the interest of LiveBot since i want to use it to "spy" on my friends.

**Comment by loogi420** [comment]
Solution to try:
Step 1: Go to Discord Developer Portal
Step 2: Click on your Application
Step 3: In the sidebar, click on the "Bot" page
Step 4: Scroll down a little, and enable all 3 settings under the "Priveleged Gateway Intents" section (Presence Intent, Server Mebers Intent and Message Content Intent)
Step 5: Reload the app (Ctrl + R)

**Comment by SebOuellette** [comment]
Closing as @loogi420 has provided the correct answer. All gateway intents must be enabled, and even then livebot can only show content that the owner of the bot would normally be able to see in discord anyway. You cannot spy on servers you are not a part of.
