### ISSUE TITLE
Cannot zoom in.

### ISSUE THREAD

**Issue by AquaQuokka** [SebOuellette/LiveBot#219]
#### What branch/release are you using?
v1.1.5 Windows

#### Errors
No Errors

#### Steps required to reproduce the bug
- Steps:
Zoom out with CTRL -
Attempt to zoom in with CTRL +
It fails to zoom in.

**Comment by yesBad** [comment]
Use CTRL SHIFT +

**Comment by AquaQuokka** [comment]
Thanks.

**Comment by AquaQuokka** [comment]
Closing now

**Comment by AquaQuokka** [comment]
Done
