### ISSUE TITLE
Not access to discord server

### ISSUE THREAD

**Issue by Justman10000** [SebOuellette/LiveBot#220]
Hi, no Discord servers are displayed even if the bot is on them:

![grafik](https://user-images.githubusercontent.com/49990629/200129987-93e1af8a-b15b-48da-9947-7ee62f2ba06a.png)

**Comment by Justman10000** [comment]
@SebOuellette

**Comment by maxi230151** [comment]
same

**Comment by Justman10000** [comment]
@SebOuellette

**Comment by SebOuellette** [comment]
You must enable all gateway intents in the discord development portal for livebot to work. 

Livebot will also only show servers that both the owner and the bot are in.

**Comment by Justman10000** [comment]
> You must enable all gateway intents in the discord development portal for livebot to work.
> 
> Livebot will also only show servers that both the owner and the bot are in.

And you closed this now because? Are we done here? I didn't know! Maybe all intents were active? But whatever, just close it! Who cares?
