### ISSUE TITLE
(MacOS) doesn't open servers, doesn't load all servers and DM's tabs doesn't work

### ISSUE THREAD

**Issue by yes-0001** [SebOuellette/LiveBot#225]
whenever I use this, 
for 1, it only shows the servers your bot has in common with your discord account
2, I can't open any of them, even if my real discord account is on the server (aka, focused on it with the discord client), and also if discord client is closed fully
3, the DM's tabs doesn't work, my bot sends me something, doesn't show on the tabs, I send the bot something, doesn't show

also I've looked at literally all bug reports, nothing works

**Comment by shakyevan444** [comment]
im on mac and it works fine

**Comment by SebOuellette** [comment]
Closing. Please refer to #227 for further discussion about this issue.
