### ISSUE TITLE
Livebot not showing 19-digit emojis and shows as plain text

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [SebOuellette/LiveBot#237]
#### What branch/release are you using?

- Branch/Release: master
#### Errors
19-digit Emojis showing as plain text

#### Steps required to reproduce the bug

- Steps:
1. See Any 19-digit Emojis

#### Screenshot (In most cases required)

- Screenshot:
![image](https://user-images.githubusercontent.com/40109698/224521437-1ace831a-e315-4351-9329-986967377660.png)

**Comment by Xaliks** [comment]
#### I can't reproduce
Make sure you are using **master** release of LiveBot. This bug has already been fixed in #210

![Screenshot](https://i.xaliks.fun/0a03ad.png "Screenshot")

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
i'm dumb, forget to update
