### ISSUE TITLE
Nothing at all shows up.

### ISSUE THREAD

**Issue by B1u3lol** [SebOuellette/LiveBot#238]
was trying to get a bot to chat, but in livebot 1.2.0 absolutely nothing shows for me, i have no idea why.
![image](https://user-images.githubusercontent.com/127780747/224784917-2944ab06-ffec-4a4e-883d-0b1dcd84fc33.png)

**Comment by SebOuellette** [comment]
Livebot will only show servers that the bot and the owner are both in. It will also only show these servers if the gateway intents are enabled for the bot.
