### ISSUE TITLE
doesn't let me see all the servers its in (my bot is in over 75 servers and it shows only 4)

### ISSUE THREAD

**Issue by 5ryh6tesjnst7ykj** [SebOuellette/LiveBot#247]
#### What branch/release are you using?

- Branch/Release:

#### Steps required to reproduce the bug

- Steps:

#### Screenshot (In most cases required)

- Screenshot:

**Comment by SebOuellette** [comment]
Due to discord's privacy policy, LiveBot can only show servers which both the bot and its owner are both in. 

Sorry for the inconvenience.
