### ISSUE TITLE
1.3.1 does not work

### ISSUE THREAD

**Issue by Reycko** [SebOuellette/LiveBot#249]
#### What branch/release are you using?

- Branch/Release: [v1.3.1-alpha](https://github.com/SebOuellette/LiveBot/releases/tag/v1.3.1-alpha)

When I try to log-in, it just gets stuck at "Logging into the bot...", I've tried all of the "Stuck loading?" steps.
#### Steps required to reproduce the bug

- Steps: Input token, then try to log in

#### Screenshot (In most cases required)

- Screenshot:

**Comment by noscamming** [comment]
no screenshot...

**Comment by SebOuellette** [comment]
Did you try everything in the "stuck loading" dropdown? Without a screenshot or any more information, I can't help much. Please open developer console by pressing ctrl+shift+i, then click Console. Screenshot any errors that appear.

**Comment by Reycko** [comment]
> Did you try everything in the "stuck loading" dropdown? Without a screenshot or any more information, I can't help much. Please open developer console by pressing ctrl+shift+i, then click Console. Screenshot any errors that appear.

it works now i think i did something wrong
