### ISSUE TITLE
All servers not showing (only 2 out of 6)

### ISSUE THREAD

**Issue by mauzdud** [SebOuellette/LiveBot#260]
My bot is in 6 servers, both gateway intents are enabled, yet only 2 show up.
![image](https://github.com/SebOuellette/LiveBot/assets/131390481/20a43441-1f00-4f7c-83e9-c1e25d1c6cf4)
![image](https://github.com/SebOuellette/LiveBot/assets/131390481/5cad6e27-2181-437d-a73d-1f138b3ac9d1)

**Comment by ci2bx** [comment]
Same here

Showing 6 out of 8

**Comment by SebOuellette** [comment]
This behavour is intentional. LiveBot only shows servers, channels, & messages that the bot's owner (creator of the bot application) can also see. This is a privacy measure to prevent users from seeing more than they should.
