### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by dcrime** [SebOuellette/LiveBot#31]
Decided to search online for emoji aliases tho I didn't find the full list so I went ahead and searched in discord itself

(The json file (Github doesn't allow .json so I'm uploading it as .txt), The first value is the regex I extracted them from)
[emojis.txt](https://github.com/SebOuellette/Discord-LiveBot/files/4198680/emojis.txt)

Suggestion
Custom emojis from other servers

**Comment by SebOuellette** [comment]
Oh thanks! This will be a huge help. 

Custom emojis will be added soon. I haven't been able to work very much recently so when I am able to, I'll add those custom emojis

**Comment by dcrime** [comment]
I just noticed that on :blush: I didn't remove the backslash so I think that's the only mistake I've done in the file

**Comment by dcrime** [comment]
All the shortcuts have been added and the custom emojis have also been added, thank you for your suggestion @dcrime
