### ISSUE TITLE
Edit messages

### ISSUE THREAD

**Issue by AllanTaylor314** [SebOuellette/LiveBot#40]
One of the great features of discord is the ability to edit messages. One use case for this in LiveBot would be updating rules. I have my bot post the rule list, but I want to be able to update them without having to find and edit the message through code; just a few clicks through LiveBot

**Comment by dcrime** [comment]
Well, the creator of this vanished, he did say he's busy but eh, anyway I went ahead and added the edit message on my fork of this though it's not pretty it works, anyway in this fork you should have a menu on the right side of the message and you can press edit, anything that is written down in the message textbox will be applied to the edit, if there's nothing written there it should paste all the text in there
https://github.com/dcrime/Discord-LiveBot

**Comment by dcrime** [comment]
O yeah, if I remember correctly there should be a limit on messages so if it's x days/months whatever old you can't edit it, also keep in mind there's a message count limit
- If you're gonna use my fork it doesn't have the executable version, just the master

**Comment by dcrime** [comment]
The ability to edit messages has been added in commit e5f6988
