### ISSUE TITLE
help

### ISSUE THREAD

**Issue by imanidiotlol** [SebOuellette/LiveBot#42]
https://user-images.githubusercontent.com/64072166/79850030-87612580-83ed-11ea-8006-baf4fd3799cd.png

**Comment by shadow173** [comment]
Try redownloading and disabling your AV

**Comment by SebOuellette** [comment]
Have you tried the executable branch?

**Comment by SebOuellette** [comment]
Is it working for you now?

**Comment by dcrime** [comment]
Since there was no reply in quite a while I'm going to close this issue
