### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by johndockinson** [SebOuellette/LiveBot#57]
I added my token, clicked save and nothing happens.
![image](https://user-images.githubusercontent.com/67174922/85187605-bfaaa600-b26e-11ea-8929-b66b145f3a6d.png)

**Comment by SebOuellette** [comment]
Can you take a screenshot of what appears in the console? You can open the console my pressing Ctrl+Shift+i

**Comment by johndockinson** [comment]
> 
> 
> Can you take a screenshot of what appears in the console? You can open the console my pressing Ctrl+Shift+i
![image](https://user-images.githubusercontent.com/67174922/85188602-00f28400-b276-11ea-922f-5fce1ccbf775.png)
Sure. This is the *only* error I get in the console.

**Comment by SebOuellette** [comment]
Whoops. Fixed in 375b8721f41b95b6bf18697795e8787c76956db0 This happens pretty much every time I update the executable branch.
