### ISSUE TITLE
"<3" is transformed into "undefined"

### ISSUE THREAD

**Issue by busybox11** [SebOuellette/LiveBot#67]
When I try to send a heart (<3), the string "undefined" is sent, not the heart.

**Comment by Erik-Lopez** [comment]
I'm new to all of this, but I might contribute. 
In LiveBot/js/converter.js the code for "<3" (line 39) is repeated. Plus it is never asigned to an emoji in idToUni (line 501). 
Apologies for my noviceness.

**Comment by busybox11** [comment]
You're right. Just made a PR.

**Comment by SebOuellette** [comment]
Fixed in latest commit
