### ISSUE TITLE
Last server keeps being displayed on top on app when switching to DMs

### ISSUE THREAD

**Issue by busybox11** [SebOuellette/LiveBot#70]
![image](https://user-images.githubusercontent.com/29630035/89899548-c1e00f80-dbe2-11ea-84c9-d5fe2ed8c82b.png)
When I'm switching over DMs, the server top bar is still displayed.

**Comment by LukasDoesDev** [comment]
Affects me as well.

**Comment by LukasDoesDev** [comment]
I fixed this btw.

**Comment by SebOuellette** [comment]
-> in a PR that wasn't accepted

**Comment by LukasDoesDev** [comment]
Yup. From Mr. PR closer.

**Comment by LukasDoesDev** [comment]
Anyway, such weird contributors calling dcrime names and using 4 wide soft tabs...

**Comment by maalos** [comment]
:OmegaLUL:

**Comment by SebOuellette** [comment]
Fixed in 57b2ae05fd19311bee3169bb08591fa12dffc0e5
