### ISSUE TITLE
User color is not the same on role list and chat

### ISSUE THREAD

**Issue by busybox11** [SebOuellette/LiveBot#71]
As you can see on the following screenshots, the color is not the same.
The user has no roles.

![image](https://user-images.githubusercontent.com/29630035/89900104-94479600-dbe3-11ea-9a33-5884d83e1dfa.png)
![image](https://user-images.githubusercontent.com/29630035/89900111-97db1d00-dbe3-11ea-9562-91b204ae6765.png)

**Comment by SebOuellette** [comment]
What roles does the user have? And what colours are those roles?

**Comment by busybox11** [comment]
No roles.

**Comment by SebOuellette** [comment]
We can't seem to replicate this issue... and it was fixed (we thought) a few commits back. Can you verify that you're still having this issue?

**Comment by dcrime** [comment]
I'm closing this issue since it's been a few days, if it's still happening feel free to re-open the issue and contact us on discord while you're encountering it so we can see exactly what's going on
