### ISSUE TITLE
app wont open

### ISSUE THREAD

**Issue by ILikeToRecycle** [SebOuellette/LiveBot#76]
whenever i try to open livebot it doesnt open at all i have all the requirements but it wont open any ideas?

**Comment by dcrime** [comment]
Hello @ILikeToRecycle would you mind explaining on what's happening in more detail, what branch etc..
Tho we'd prefer it if you [Joined the discord server](https://discord.gg/TMUc8Bs) for us to be able to assist you better

**Comment by ILikeToRecycle** [comment]
@dcrime ill join the discord server and ask 😄

**Comment by dcrime** [comment]
From the server it seems your issue has been resolved (ffmpeg.dll issue) so I'm closing this issue.
Thank you for using LiveBot!
