### ISSUE TITLE
it wont open and it gives me a console prompt

### ISSUE THREAD

**Issue by StonksSelected** [SebOuellette/LiveBot#77]
![image](https://user-images.githubusercontent.com/62770315/90343045-eeda5b00-e004-11ea-8727-959088af7232.png)

**Comment by SebOuellette** [comment]
Use `npm test` instead of `npm start`

**Comment by StonksSelected** [comment]
i found the solution i switched from master to .exe

**Comment by SebOuellette** [comment]
The executable version is very out of date, if you want the latest features, make sure to use master
