### ISSUE TITLE
Animated server pictures are not animated 

### ISSUE THREAD

**Issue by busybox11** [SebOuellette/LiveBot#78]
I don't know if it also occurs with user profile pictures, I only noticed this behavior with servers.

**Comment by dcrime** [comment]
Animated server icons haven't been implemented yet, [please use the discord server to post your suggestions and ask questions about LiveBot since you're already in it](https://discord.gg/TMUc8Bs)

**Comment by dcrime** [comment]
Oh, I didn't close this yet, seems like I forgot while getting the commit, anyway.

Animated server icons have been added in the commit bcaf805 along with other changes.
