### ISSUE TITLE
[BUG] Nothing works

### ISSUE THREAD

**Issue by Splatterxl** [SebOuellette/LiveBot#79]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?
- Branch: Master

#### What type of bug is it?
 - Type: All
#### Steps required to reproduce the bug
- Steps: Log in with NzQ0NjU5MjE5MDY3OTYxMzU0.Xzmb8A.D8IYxP8RKW61cVcJ1GktQenOZmk. I don't care what you do with my bot.

#### Screenshot (In most cases required)

- Screenshot: https://cdn.discordapp.com/attachments/730883596453150792/749668236873957526/unknown.png

**Comment by SebOuellette** [comment]
Yeaa..... the server icon and your bot icon are both transparent. Idk what the plan here was but. Sure.

**Comment by dcrime** [comment]
But yes, in fact there are stuff that aren't working correctly
#verify-here - There's an inline block which is making the other parsing not happen, correct
And also pings aren't working, so congrats on finding that out
So yes, just because you did this it doesn't mean we don't know what's happening
