### ISSUE TITLE
It's not working at all

### ISSUE THREAD

**Issue by MoDerPo** [SebOuellette/LiveBot#83]
#### How major is the bug from 1 - 10
- Scale: 9

#### What branch are you using?

- Branch: executable
#### What type of bug is it?

- Type: UI
#### Steps required to reproduce the bug

- Steps: Downloadoaded the executable zip. Laucnched LiveBot.exe.

#### Screenshot (In most cases required)

- Screenshot:
![image](https://user-images.githubusercontent.com/69361959/97536182-119dce00-19bd-11eb-9f80-ddf272546c1c.png)

**Comment by MMK21Hub** [comment]
> Please don't just say 'this seems like a bug' and leave everyone else to figure out what the bug is.

What is the actual problem?

**Comment by SebOuellette** [comment]
The executable branch is currently broken, I'm going to fix it as soon as I can, but for now try using the master branch

**Comment by yuto0214w** [comment]
(Do you have both you and your bot in your server?
For some reasons you can only see servers that both you and your bot are in)

**Comment by benhdev** [comment]
@SebOuellette Master branch is broken too

**Comment by SebOuellette** [comment]
Yuto that's not the problem, I know the executable Branch is broken, I just haven't gotten around to fixing it

**Comment by SebOuellette** [comment]
@benhdev the matter branch is not broken, but it does seem like it. Discord changed the way bots worked and so now to use livebot you must enable privileged intents in the discord application menu. Join our discuss server of you have any further questions.

**Comment by SebOuellette** [comment]
Executable branch has been updated and is now functioning

**Comment by MoDerPo** [comment]
> > Please don't just say 'this seems like a bug' and leave everyone else to figure out what the bug is.
> 
> What is the actual problem?

well I don't know! I told you everything i know
