### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rego0116** [SebOuellette/LiveBot#84]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: master
#### What type of bug is it?

- Type: Visual
#### Steps required to reproduce the bug

- Steps: Opened it using npm test and it happened

#### Screenshot (In most cases required)

- Screenshot: https://drive.google.com/file/d/1TpOvQ9YQnQoNim0fnRKHjK5zpz5BAz00/view?usp=sharing

**Comment by MMK21Hub** [comment]
> # Please don't just say 'this seems like a bug' and leave everyone else to figure out what the bug is.

**Comment by Rego0116** [comment]
The problem is that it just happened. I did not do anything to trigger it, I just opened it. I waited 2 hours and it was just stuck on that screen.

**Comment by SebOuellette** [comment]
-- This issue was solved in the discord channel, the problem was that the bot was not in any servers, and both privilaged intents were not enabled.
