### ISSUE TITLE
How can I deploy this (such as repl.it)

### ISSUE THREAD

**Issue by Outersloth** [SebOuellette/LiveBot#85]
#### How major is the bug from 1 - 10
- Scale: 7

#### What branch are you using?
Master
- Branch:
#### What type of bug is it?

- Type: I'm not to sure
#### Steps required to reproduce the bug

- Steps: Maybe a response on how to make this like a website

#### Screenshot (In most cases required)

- Screenshot:

**Comment by SebOuellette** [comment]
We don't have a way of doing this. You need to run this on your local machine.

**Comment by SebOuellette** [comment]
This is also not a bug
If you have a question like this, please ask in the discord server linked on the main readme.
