### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by dcadarko** [SebOuellette/LiveBot#87]
I would like to suggest adding an option to minimize the live bot application to system tray. Since it is an electron.js app, i found a resource that might help: https://www.electronjs.org/docs/api/tray

**Comment by SebOuellette** [comment]
As the label says, please use discord. I'll close this since this isn't the right place for suggestions

**Comment by Splatterxl** [comment]
Discord is not the right place for suggestions.

The GitHub Issues section is. This section is for suggestions and bugs, not just bugs.

**Comment by SebOuellette** [comment]
I understand that you may prefer something different from what I do, but I prefer to have everything sorted so that suggestions are in discord, and actual issues, that take priority, go here.
