### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vladko56** [SebOuellette/LiveBot#88]
#### How major is the bug from 1 - 10
- Scale: 
9
#### What branch are you using?

- Branch:executable
#### What type of bug is it?

- Type: visual
#### Steps required to reproduce the bug

- Steps:opening the app
![snip](https://user-images.githubusercontent.com/73774124/98267069-a42d0700-1f93-11eb-895d-c73894a69560.PNG)

#### Screenshot (In most cases required)

- Screenshot:
hello, if i open the app, the dms are not shown, this maybe not a bug, i think i need  to do something to activate dms? also, i named my bot spambot random.

**Comment by SebOuellette** [comment]
Is your bot in any servers?

**Comment by Vladko56** [comment]
Yes. 2 servers

**Comment by SebOuellette** [comment]
have you enabled both of the gateway intents on the discord application panel?

**Comment by Vladko56** [comment]
like manage servers and administrator? sorry im kinda new and not really knowing what are you talking about

**Comment by Vladko56** [comment]
update: i could use the bot to send and recieve messages but after restarting the app i couldnt anymore.

**Comment by SebOuellette** [comment]
[Take a look at this image](https://images.soue.ca/FUb61BJitz.png)

**Comment by Vladko56** [comment]
okay, going to enable and let you know if it works

**Comment by Vladko56** [comment]
livebot application is stuck at loading scripts, is it normal btw?

**Comment by Vladko56** [comment]
i am going to reinstall it, maybe thats the problem

**Comment by Vladko56** [comment]
thanks dude,works

**Comment by SebOuellette** [comment]
Oh great
