### ISSUE TITLE
[BUG] Electron fails to install

### ISSUE THREAD

**Issue by NOTANO0B** [SebOuellette/LiveBot#89]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: master
#### What type of bug is it?

- Type: usability
#### Steps required to reproduce the bug

- Steps: fix electron

#### Screenshot (In most cases required)

- Screenshot:

Electron is broken, each time i install electronl it tells me I have to delete and download again

**Comment by SebOuellette** [comment]
Sorry this is not something I can help you with since I didn't make electron, you should go to [the electron repository](https://github.com/electron/electron) to get help.
