### ISSUE TITLE
Miscellanious things to make it more viewable

### ISSUE THREAD

**Issue by taikutsunan** [SebOuellette/LiveBot#9]
A list of things that should _maybe_ be the next step
- Add markdown support
- Add clickable links
- Add viewing embedded images
- Add viewed emojis

**Comment by PlayBy** [comment]
That would be good to add, however I have stopped production of this, so I will not be adding anything or taking suggestions.

**Comment by GreatGodApollo** [comment]
If you don't mind me asking, why have you stopped developing this? It's much better than any of the other implementations that I have seen.

**Comment by PlayBy** [comment]
Well I may start it again since so many people are requesting features, but it's just a timing issue. I'll see what I can do

**Comment by SylveonBottle** [comment]
As you have restarted production of this app, will you be re-opening this issue? Or shall we just remake a new one with the same suggestions?

**Comment by SebOuellette** [comment]
These old reccomendations have been added to a Trello page, so they will all be added at some point

**Comment by SebOuellette** [comment]
As of commit 293f768693757d230729f7f74dba0a16cebbae14 (at least) this have all been added. If you have any more suggestions, feel free to leave them in the discord server, so where we will get to them faster. :)
