### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nemesisgaming12** [SebOuellette/LiveBot#96]
#### How major is the bug from 1 - 10
- Scale:  10
eg i cant use it at all
#### What branch are you using?

- Branch: executable
#### What type of bug is it?

- Type:  Visual?
#### Steps required to reproduce the bug

- Steps: Start up the client, log in

#### Screenshot (In most cases required)
![image](https://user-images.githubusercontent.com/25161459/100673409-83e84080-33b7-11eb-9ab2-3ab8edff9bdd.png)

I cannot view any servers, and my bot is in at least 6

**Comment by nemesisgaming12** [comment]
found the problem

**Comment by SebOuellette** [comment]
Ah, well glad you solved it haha
