### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by imadethisaccountsoicanmakeanissue** [SebOuellette/LiveBot#98]
I can't use it.
![image](https://user-images.githubusercontent.com/75588579/101294299-0b7ce780-37dc-11eb-901d-f09e4819ae5d.png)

**Comment by SebOuellette** [comment]
Thanks for making this issue!

Is your bot in any servers? And is your bot in any servers that you are also in?
Discord staff contacted us and we can only show servers that the bot and the owner of the bot (likely you) have in common.

If yes, then have you enabled both gateway intents?

**Comment by SebOuellette** [comment]
_This means it won't work if you're [token stealing](https://images.soue.ca/1rpWQrX0Vz.png)_

**Comment by imadethisaccountsoicanmakeanissue** [comment]
yes
its in MY server

**Comment by imadethisaccountsoicanmakeanissue** [comment]
and no i dont think so

**Comment by imadethisaccountsoicanmakeanissue** [comment]
also the token steal is for other stuf

**Comment by imadethisaccountsoicanmakeanissue** [comment]
here's proof i own it
![image](https://user-images.githubusercontent.com/75588579/101297161-17bd7080-37ed-11eb-816a-4e7fe1a3741e.png)

**Comment by imadethisaccountsoicanmakeanissue** [comment]
> Thanks for making this issue!
> 
> Is your bot in any servers? And is your bot in any servers that you are also in?
> Discord staff contacted us and we can only show servers that the bot and the owner of the bot (likely you) have in common.
> 
> If yes, then have you enabled both gateway intents?

it worked yay thanks
