### ISSUE TITLE
[BUG] I can't see servers in the server list despite my bot being in multiple.

### ISSUE THREAD

**Issue by Qiblox** [SebOuellette/LiveBot#99]
#### How major is the bug from 1 - 10
- Scale: 10

#### What branch are you using?

- Branch: Master
#### What type of bug is it?

- Type: Visual (?)
#### Steps required to reproduce the bug

- Steps: N/A

#### Screenshot (In most cases required)

- Screenshot:
![image](https://user-images.githubusercontent.com/59796293/101506632-fc1cac00-394b-11eb-8898-7935e9a55c42.png)
![image](https://user-images.githubusercontent.com/59796293/101506729-18b8e400-394c-11eb-9349-58c07045e83a.png)

**Comment by SebOuellette** [comment]
Have you enabled gateway intents?

**Comment by Qiblox** [comment]
Pretty sure, just to double check, how would you go about that?

**Comment by SebOuellette** [comment]
It's on the applications page. [here is an example](https://images.soue.ca/IGB0f3qF0y.png)

**Comment by Qiblox** [comment]
Oops, guess I didn't save it when I enabled it last time when creating the bot originally. My mistake, thanks for the assistance nonetheless.

**Comment by SebOuellette** [comment]
No problem, if it's working for you then you can close the issue now, otherwise if you need more help then ask away!

Glad I could help!

**Comment by Qiblox** [comment]
Nothing more I need to add, glad to see you still supporting the project and solving issues like this one which ended up just me being mistaken.

Have a good rest of your day.
